### ISSUE TITLE
spec suggests otherwise

### ISSUE THREAD

**Issue by princemaple** [cabol/ex_shards#7]
Hi @cabol ,

https://github.com/cabol/ex_shards/blob/master/lib/ex_shards.ex#L91
This line of spec seems to be wrong.

In my test it seems to return `value` directly, not a tuple. I'm not sure what the intended behavior is. Also, when would it ever be `[value]`?

**Comment by cabol** [comment]
Hi @princemaple, you're right, there is an error in that spec, I'll fix it right away.

On other hand, it returns `[value]` when you have a `bag` or `duplicate_bag` tables.

**Comment by cabol** [comment]
@princemaple the spec is fixed -> https://github.com/cabol/ex_shards/blob/master/lib/ex_shards.ex#L91

Let me know if we can close this issue, stay tuned!

Thanks !!

**Comment by princemaple** [comment]
Thank you!

**Comment by princemaple** [comment]
Please take a look at https://github.com/cabol/ex_shards/pull/6 also :)
